INSERT INTO Customers VALUES (1, 'DUPOND', 'JEAN');
INSERT INTO Customers VALUES (2, 'VANLAST', 'MARC');
INSERT INTO Customers VALUES (3, 'DOE', 'JOHN');
INSERT INTO Customers VALUES (4, 'MACLAREN', 'ENZO');
INSERT INTO Customers VALUES (5, 'FARLAN', 'DIEGO');
INSERT INTO Customers VALUES (6, 'LOGAN', 'PAUL');